matrix:
  include:
    - language: go
      go: "1.10.3"
      script:
        - make -B backend

    - language: node_js
      node_js: "10.9.0"
      before_script:
        - yarn
      script:
        - make -B frontend

