matrix:
  include:
    - language: go
      go: "1.10.3"
      script:
        - make

    - language: node_js
      node_js: "10.9.0"
      before_script:
        - echo "before_script"
      script:
        - echo "script"

