matrix:
  include:
    - language: go
      go: "1.10.3"
      before_script:
        - nvm install 10.9.0
        - yarn
        - yarn global add webpack-cli webpack
      script:
        - make build/wifi-raspberry
        - make build/static/main.js

